### ISSUE TITLE
Bug: loads broken on Python 3.12 and 3.13

### ISSUE THREAD

**Issue by davidosterberg** [victorazzo/abdbeam#8]
The example in the readme.txt  crash on Python 3.12 and above.

![image](https://github.com/user-attachments/assets/521c88d2-27ea-40a3-92a9-0b35e5a4378f)

I think the issue is a bug in pandas: (https://github.com/pandas-dev/pandas/issues/58604)

**Comment by victorazzo** [comment]
@davidosterberg - thanks for flagging. Will try to reproduce and check the fix as suggested this weekend.

**Comment by davidosterberg** [comment]
Repeating what is said in the pandas issues: the error is due to the way in which Pandas handles the [:] indexer in Python 3.12. This comes from a https://github.com/python/cpython/pull/101264 in Python 3.12 which makes slice objects hashable.
